version: '2.1'

services:
  snl-api-db:
    container_name: snl-api-db
    build: ./docker/snl-api-db
    networks:
      - snl-network
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=snluser
      - POSTGRES_PASSWORD=snlpass
      - POSTGRES_DB=snl
  snl-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: docker.artifactory.reform.hmcts.net/reform/snl-api
    container_name: snl-api
    depends_on:
      - snl-api-db
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - SNL_EVENTS_URL=http://host.docker.internal:8092
      - SNL_API_DB_HOST=host.docker.internal
      - SNL_API_DB_PORT=5434
      - SNL_API_DB_NAME=snl
      - SNL_API_DB_USERNAME=snluser
      - SNL_API_DB_PASSWORD=snlpass
    ports:
      - 8090:8090
    networks:
      - snl-network
networks:
  snl-network:
    driver: bridge
    name: snl-network

